name: Build and Push earth-observations-snap

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/earth-observations.yaml'
      - 'Dockerfile'

jobs:
  build-push:
    name: earth-observations-snap
    uses: ./.github/workflows/build-push.yaml
    with:
      image_name: earth-observations-snap
    secrets:
      workload_identity_provider: ${{secrets.WORKLOAD_IDENTITY_PROVIDER}}
      workload_identity_sa: ${{secrets.WORKLOAD_IDENTITY_SA}}